[program:pocketbase]
command=/app/pocketbase/pocketbase serve --http=127.0.0.1:8090 --dir=/app/pocketbase/pb_data
directory=/app/pocketbase
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/pocketbase.err.log
stdout_logfile=/var/log/supervisor/pocketbase.out.log
stopsignal=TERM
stopwaitsecs=15
stopasgroup=true
killasgroup=true
