export const TRAINER_PLANS = [
{id:'forca-pit-1',category:'FORÇA',title:'Força · Pit + unilateral',subtitle:'Força general + bloc aeròbic',sections:[{title:'Força',items:[['Press banca','4 × 12'],['Remo mancuerna unilateral','4 × 12'],['Zancada frontal amb 2 manuelles','4 × 15 passos']]},{title:'Bloc aeròbic',items:[['800 m córrer','3 rondes'],['1\'15" salt a la corda','3 rondes'],['15 toes to bar','3 rondes']]}]},
{id:'nadar-1',category:'NATACIÓ',title:'Nadar · Aeròbic + crol',subtitle:'Trote suau + piscina',sections:[{title:'Objectiu del cardio',items:[['20 min trote suau',''],['200 m variats','Piscina'],['4 × 25 crol fort','d/40" · 3 blocs'],['100 m suau','Després de cada bloc'],['300 m molt suau','Variant entre crol, esquena i peus · (A) aletes']]}]},
{id:'correr-intervals-1',category:'CÓRRER',title:'Córrer · Respiració nasal',subtitle:'Treball aeròbic controlat',sections:[{title:'Objectiu del cardio',items:[['4 min córrer','Pensant molt en la respiració nasal · 4 rondes'],['1 min caminar','Després de cada 4 min · 4 rondes']]}]},
{id:'forca-cames-1',category:'FORÇA',title:'Força · Cames + cadena posterior',subtitle:'Força + bloc aeròbic',sections:[{title:'Força',items:[['Sentadilla frontal (Front Squat)','4 × 12'],['Peso muerto rumano','4 × 12'],['Marxa del granger amb KB','4 × 40"']]},{title:'Bloc aeròbic',items:[['500 m rem aeròbic','3 rondes'],['20 burpees','3 rondes'],['20" battle rope','3 rondes']]}]},
{id:'forca-pit-2',category:'FORÇA',title:'Força · Pit + tracció',subtitle:'Força + bloc aeròbic',sections:[{title:'Força',items:[['Press banca','4 × 12'],['Rack Chin (TRX)','4 × 12'],['Zancada frontal amb 2 manuelles','4 × 15 passes']]},{title:'Bloc aeròbic',items:[['1000 m córrer','2 rondes'],['1 min salt a la corda','2 rondes'],['15 toes to bar','2 rondes']]}]},
{id:'bici-regenerativa',category:'BICI',title:'Ciclisme · Regeneratiu',subtitle:'Volum cardiovascular sense impacte',sections:[{title:'Objectiu del cardio',items:[['1 h de bici','Ritme molt fàcil · regeneratiu']]}]},
{id:'test-5k',category:'CÓRRER',title:'Test 5K · Ritme còmode',subtitle:'Test controlat',sections:[{title:'Objectiu del cardio',items:[['5 km corrent','Ritme còmode · veure com puja el pols a ritme mitjà · ritme estable · no mirar temps durant, només final · després passar report']]}]},
{id:'circuit-pes-corporal',category:'MANTENIMENT',title:'Circuit · Pes corporal + KB',subtitle:'Circuit curt de manteniment',sections:[{title:'Circuit',items:[['Flexions','2 × màxim'],['Goblet squat','2 × 30"'],['Dominades','2 × màx. repeticions'],['Swing','2 × 30"'],['Planxa 3 suports','2 × 30"'],['Planxa lateral 2 suports','2 × 30" × costat']]}]},
{id:'nadar-tecnica-1',category:'NATACIÓ',title:'Nadar · Tècnica i peus',subtitle:'Variats + crol',sections:[{title:'Objectiu del cardio',items:[['200 m variat estils',''],['4 × 50 peus de braç','25 peus de braç + 25 crol · d/20"'],['4 × 25 GRAVAT nedant',"1 crol lateral · 1 braç · 1 esquena amb peus de braç · 1 crol per davant · d/1'"]]}]},
{id:'forca-base',category:'FORÇA',title:'Força base · Trap Bar + unilateral',subtitle:'Força global',sections:[{title:'Força Base',items:[['Peso muerto amb barra hexagonal (Trap Bar)','4 × 5'],['Dominades','4 × 4'],['Landmine unilateral en lunge','4 × 6'],['Remo amb barra en banc · agafada prona','4 × 8'],['Hip thrust en banc','4 × 8']]}]},
{id:'nadar-apnea',category:'NATACIÓ',title:'Nadar · Apnea + control',subtitle:'Treball específic de piscina',sections:[{title:'Objectiu del cardio',items:[['400 m variats',''],['4 × 75 crol','Buscant agafar aigua des de l’inici de la braçada · d/20"'],['4 × 50 peus (A) (T)','Braços quiets i estirats davant · d/20" · 2 blocs'],['4 × 15 m apnea',"Tocant el terra als 10 m · acabar piscina nedant · d/1' · 2 blocs"],['100 suaus','Final']]}]},
{id:'forca-superserie-core',category:'FORÇA',title:'Força · Supersèrie + core',subtitle:'2 rondes',sections:[{title:'SUPERSET ×2 RONDES',items:[['90-90 aixecant maluc en OK','5 × costat'],['Flexor de maluc + peso mort unilateral','5 × costat'],['Peso mort de genolls i goma','10'],['Activació de flexors de maluc + core amb goma','10 × costat']]},{title:'Test incendi vegetació fase 3',items:[['12 rectes de 20 m',''],['24 llançaments amb pilota medicinal','6 kg']]}]},
{id:'bici-volum',category:'BICI',title:'Ciclisme · Volum',subtitle:'Sessió fàcil per sumar volum',sections:[{title:'Objectiu del cardio',items:[['1 h 30 min de bici','Fàcil · sumar volum cardiovascular sense impacte · ritme fàcil progressant a ritme mig']]}]},
];
export const TRAINER_PLAN_CATEGORIES=['TOTS',...new Set(TRAINER_PLANS.map((p)=>p.category))];
export const getTrainerPlan=(id)=>TRAINER_PLANS.find((plan)=>plan.id===id)||null;
