import React,{useMemo,useState} from 'react';
import Helmet from 'react-helmet';
import {Link,useNavigate} from 'react-router-dom';
import AppShell from '@/components/AppShell';
import {TRAINER_PLAN_CATEGORIES,TRAINER_PLANS} from '@/lib/trainerPlans';
const categoryStyle={FORÇA:'border-orange-200 bg-orange-50 text-orange-800',NATACIÓ:'border-sky-200 bg-sky-50 text-sky-800',CÓRRER:'border-rose-200 bg-rose-50 text-rose-800',BICI:'border-emerald-200 bg-emerald-50 text-emerald-800',MANTENIMENT:'border-violet-200 bg-violet-50 text-violet-800'};
export default function TrainerPlansPage(){
 const [filter,setFilter]=useState('TOTS'); const [open,setOpen]=useState(null); const navigate=useNavigate();
 const plans=useMemo(()=>filter==='TOTS'?TRAINER_PLANS:TRAINER_PLANS.filter((p)=>p.category===filter),[filter]);
 return <AppShell title="PAUTES ENTRENADOR"><Helmet><title>Pautes de l’entrenador — BOMBER TRAINER</title></Helmet>
  <section className="rounded-3xl bg-slate-900 p-5 text-white shadow-sm"><p className="text-xs font-black tracking-[0.2em] text-orange-300">BOMBER TRAINER · PAUTES</p><h1 className="mt-2 text-2xl font-black">La pauta queda guardada aquí.</h1><p className="mt-2 text-sm font-medium leading-6 text-slate-200">Sessions guardades dins l’app per poder-les consultar i repetir encara que algun dia no tinguis accés a l’entrenador.</p><div className="mt-4 flex flex-wrap gap-2"><span className="rounded-full bg-white/10 px-3 py-1.5 text-xs font-bold">{TRAINER_PLANS.length} sessions</span><span className="rounded-full bg-white/10 px-3 py-1.5 text-xs font-bold">Força · cardio · piscina · bici</span></div></section>
  <div className="mt-4 flex gap-2 overflow-x-auto pb-1" role="tablist">{TRAINER_PLAN_CATEGORIES.map((c)=><button key={c} type="button" onClick={()=>setFilter(c)} className={`min-h-[44px] shrink-0 rounded-full border px-4 text-xs font-black ${filter===c?'border-slate-900 bg-slate-900 text-white':'border-slate-200 bg-white text-slate-600'}`}>{c}</button>)}</div>
  <div className="mt-4 space-y-3">{plans.map((plan)=>{const isOpen=open===plan.id;return <article key={plan.id} className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm"><button type="button" onClick={()=>setOpen(isOpen?null:plan.id)} className="w-full p-5 text-left"><div className="flex items-start justify-between gap-3"><div><span className={`inline-flex rounded-full border px-2.5 py-1 text-[10px] font-black tracking-wider ${categoryStyle[plan.category]||'border-slate-200 bg-slate-50 text-slate-700'}`}>{plan.category}</span><h2 className="mt-2 text-lg font-black text-slate-900">{plan.title}</h2><p className="mt-1 text-sm font-medium text-slate-500">{plan.subtitle}</p></div><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-slate-100 text-xl font-bold">{isOpen?'−':'+'}</span></div></button>
 {isOpen&&<div className="border-t border-slate-200 bg-slate-50 p-4"><div className="space-y-3">{plan.sections.map((section)=><section key={section.title} className="rounded-2xl border border-slate-200 bg-white p-4"><h3 className="text-sm font-black uppercase tracking-wider text-slate-500">{section.title}</h3><div className="mt-3 space-y-2">{section.items.map(([name,target])=><div key={name} className="flex items-start justify-between gap-3 rounded-xl bg-slate-50 px-3 py-3"><span className="text-sm font-bold text-slate-800">{name}</span>{target&&<span className="shrink-0 text-right text-xs font-extrabold text-slate-500">{target}</span>}</div>)}</div></section>)}</div><div className="mt-4 grid gap-2 sm:grid-cols-2"><button type="button" onClick={()=>navigate(`/entrena/manteniment?trainerPlan=${encodeURIComponent(plan.id)}`)} className="min-h-[50px] rounded-2xl bg-slate-900 px-4 text-sm font-black text-white">▶ Començar i registrar</button><Link to="/progres" className="flex min-h-[50px] items-center justify-center rounded-2xl border border-slate-200 bg-white px-4 text-sm font-black text-slate-700">↗ Veure progrés / històric</Link></div></div>}</article>})}</div>
 </AppShell>;
}