import React, { lazy, Suspense, useEffect } from 'react';
import { Toaster } from "@/components/ui/toaster";
import { QueryClientProvider } from '@tanstack/react-query';
import { queryClientInstance } from '@/lib/query-client';
import { BrowserRouter as Router, Route, Routes, Navigate } from 'react-router-dom';
import PageNotFound from './PageNotFound';
import { AuthProvider, useAuth } from '@/lib/AuthContext';
import UserNotRegisteredError from '@/components/UserNotRegisteredError';
import ScrollToTop from './components/ScrollToTop';
import ProtectedRoute from '@/components/ProtectedRoute';
import NutritionDaily from './components/NutritionDaily';
import ProgressVisualFixes from './components/ProgressVisualFixes';
import { logAuthenticatedAccess } from './accessLogger';
const HomePage = lazy(() => import('./pages/HomePage')); const LoginPage = lazy(() => import('./pages/LoginPage')); const TrainPage = lazy(() => import('./pages/TrainPage')); const MaintenancePage = lazy(() => import('./pages/MaintenancePage')); const ProgressPage = lazy(() => import('./pages/ProgressPage')); const ProfilePage = lazy(() => import('./pages/ProfilePage')); const AiPage = lazy(() => import('./pages/AiPageAuto')); const SettingsPage = lazy(() => import('./pages/SettingsPage')); const ActivitiesPage = lazy(() => import('./pages/ActivitiesPage')); const Register = lazy(() => import('./pages/Register')); const ForgotPassword = lazy(() => import('./pages/ForgotPassword')); const ResetPassword = lazy(() => import('./pages/ResetPassword')); const OAuthCallback = lazy(() => import('./pages/OAuthCallback')); const AdminAccessPage = lazy(() => import('./pages/AdminAccessPage'));
function RouteFallback(){return <div className="fixed inset-0 flex items-center justify-center bg-slate-50" role="status" aria-live="polite"><div className="text-center"><div className="mx-auto h-8 w-8 animate-spin rounded-full border-4 border-slate-200 border-t-slate-800"/><p className="mt-3 text-sm font-semibold text-slate-500">Carregant…</p></div></div>}
const AuthenticatedApp=()=>{const {user,isLoadingAuth,isLoadingPublicSettings,authError,navigateToLogin}=useAuth();useEffect(()=>{if(!isLoadingAuth&&user)logAuthenticatedAccess(user);},[user,isLoadingAuth]);if(isLoadingPublicSettings||isLoadingAuth)return <RouteFallback/>;if(authError){if(authError.type==='user_not_registered')return <UserNotRegisteredError/>;if(authError.type==='auth_required'){navigateToLogin();return null;}}return <Suspense fallback={<RouteFallback/>}><Routes><Route path="/login" element={<LoginPage/>}/><Route path="/register" element={<Register/>}/><Route path="/forgot-password" element={<ForgotPassword/>}/><Route path="/reset-password" element={<ResetPassword/>}/><Route path="/oauth/callback" element={<OAuthCallback/>}/><Route path="/admin/accessos" element={<AdminAccessPage/>}/><Route element={<ProtectedRoute unauthenticatedElement={<Navigate to="/login" replace/>}/> }><Route path="/" element={<HomePage/>}/><Route path="/entrena/manteniment" element={<MaintenancePage/>}/><Route path="/entrena/:type" element={<TrainPage/>}/><Route path="/progres" element={<ProgressPage/>}/><Route path="/perfil" element={<ProfilePage/>}/><Route path="/ia" element={<AiPage/>}/><Route path="/activitats" element={<ActivitiesPage/>}/><Route path="/configuracio" element={<SettingsPage/>}/></Route><Route path="*" element={<PageNotFound/>}/></Routes></Suspense>};
function App(){return <AuthProvider><QueryClientProvider client={queryClientInstance}><Router><ScrollToTop/><AuthenticatedApp/><NutritionDaily/><ProgressVisualFixes/></Router><Toaster/></QueryClientProvider></AuthProvider>}
export default App;
